import Header from '@/components/header/Header'
import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import Footer from '@/components/footer/Footer'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
